<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>featpose</name>
  <version>0.1.0</version>
  <description>A package containing some inference nodes and sample models for 6D pose estimation
    using feature detection.</description>
  <maintainer email="root.link.sky@gmail.com">Leonhart Root</maintainer>
  <license file="LICENSE">Apache-2.0</license>

  <url type="repository">https://github.com/verithm/featpose</url>
  <url type="bugtracker">https://github.com/verithm/featpose/issues</url>
  <author email="root.link.sky@gmail.com">Leonhart Root</author>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>python3-scipy</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>